DDCE-4964 Create new views, routes and use session keys for new limit…
hmrc/bc-passengers-frontend pull request #450
Opened 2024-02-13 12:00 UTC by mywyau

… exceeded content

2024-02-15 09:22 UTC, gastonracui requested changes

2024-02-15 10:09 UTC, mywyau commented on app/util.scala
> +  def cigaretteAndHeatedTobaccoConstraint(numberOfSticks: Int): Boolean = numberOfSticks <= 800
done

2024-02-15 10:09 UTC, mywyau commented on app/util.scala
> +      case "cigarillos" => numberOfSticks <= 400
done

2024-02-15 10:18 UTC, mywyau commented on app/utils/FormatsAndConversions.scala
> +    def format2dps: BigDecimal =
done

2024-02-15 10:18 UTC, mywyau commented on app/views/LimitExceededViewUtils.scala
> +      case "1.00" | "1" | "1.000" => singular
done

2024-02-15 10:27 UTC, mywyau commented on app/controllers/LimitExceedController.scala
> +                  userInput = userInputBigDecimalFormatted.toString(),
done

2024-02-16 09:05 UTC, gastonracui approved these changes

2024-02-19 14:57 UTC, merged