Passengers - Prompt added to when country field is empty
hmrc/bc-passengers-frontend pull request #461
Opened 2024-08-07 14:15 UTC by Divya-Manivannan-hmrc

2024-08-08 15:03 UTC, EdCope requested changes
Please try to update the dependencies. Leave the `accessible-autocomplete` for now as it is a [major version](https://github.com/alphagov/accessible-autocomplete/releases/tag/v3.0.0#:~:text=17420f3-,Breaking%20changes,-Verify%20your%20code) with potentially breaking changes

2024-08-08 15:12 UTC, Divya-Manivannan-hmrc commented on conf/messages.cy
> +label.select_a_country = Dewiswch wald
changed the spelling and moved it up

2024-08-08 15:43 UTC, Divya-Manivannan-hmrc commented on app/views/tobacco/tobacco_input.scala.html
> +                  hint = messages("label.enter_currency"),
I changed it to hintText

2024-08-13 09:35 UTC, EdCope approved these changes

2024-08-13 09:38 UTC, merged